#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: hb://todo-service

types:
  TodoItem:
    type: object
    properties:
      id: string
      content: string

  NewTodoItem:
    type: object
    properties:
      content: string

  TodoList:
    type: object
    properties:
      title: string
      items: TodoItem[]

/todo-list:
  get:
    responses:
      200:
        body:
          type: TodoList

  post:
    body:
      type: NewTodoItem

  /{id}:
    delete:
