#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: http://example

types:
  Conditional:
    type: object
    properties:
      if?:

  WithUri:
    type: object
    properties:
      uri:

annotationTypes:
#  x-client-ip: nil | Conditional
#  x-client-language: nil | Conditional
#  deny: nil | Conditional
  rewrite: [WithUri, Conditional]

/my-todo-list:
  (rewrite):
    uri: hb://todo-service/todo-list
